/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../app/services/facebook.service';
import * as import11 from '../../app/services/auth.service';
import * as import12 from '../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import13 from '../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from '@angular/forms/src/directives/ng_form';
import * as import27 from '@angular/forms/src/directives/control_container';
import * as import28 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ld-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.FacebookService,this.parentIndex),this.injectorGet(import11.AuthService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('ld-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _NgForm_18_3:import12.Wrapper_NgForm;
  _ControlContainer_18_4:any;
  _NgControlStatusGroup_18_5:import13.Wrapper_NgControlStatusGroup;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import14.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _NgModel_22_5:import15.Wrapper_NgModel;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import13.Wrapper_NgControlStatus;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _NgForm_35_3:import12.Wrapper_NgForm;
  _ControlContainer_35_4:any;
  _NgControlStatusGroup_35_5:import13.Wrapper_NgControlStatusGroup;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  /*private*/ _vc_75:import16.ViewContainer;
  _RouterOutlet_75_5:import17.Wrapper_RouterOutlet;
  _text_76:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container page-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'nav',new import3.InlineArray2(2,'class','navbar navbar-toggleable-md fixed-top navbar-light bg-primary'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray16(14,'aria-controls','navbarResponsive','aria-expanded','false','aria-label','Toggle navigation','class','navbar-toggler','data-target','#navbarResponsive','data-toggle','collapse','type','button'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'class','navbar-toggler-icon'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbarResponsive'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'a',new import3.InlineArray4(4,'class','navbar-brand','href','/'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Law Debate',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','nav navbar-nav mr-auto'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_18_3 = new import12.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_18_4 = this._NgForm_18_3.context;
    this._NgControlStatusGroup_18_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_18_4);
    this._text_19 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','input-group mb-2 mr-sm-2 mb-sm-0'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                            ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'input',new import3.InlineArray8(8,'class','form-control form-control-xs','name','search','placeholder','Search for...','type','text'),(null as any));
    this._DefaultValueAccessor_22_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._DefaultValueAccessor_22_3.context];
    this._NgModel_22_5 = new import15.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._NgModel_22_5.context;
    this._NgControlStatus_22_7 = new import13.Wrapper_NgControlStatus(this._NgControl_22_6);
    this._text_23 = this.renderer.createText(this._el_20,'\n                            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_20,'span',new import3.InlineArray2(2,'class','input-group-btn'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'button',new import3.InlineArray4(4,'class','btn btn-secondary','type','submit'),(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'i',new import3.InlineArray2(2,'class','fa fa-search'),(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','nav navbar-nav ml-auto'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_35_3 = new import12.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_35_4 = this._NgForm_35_3.context;
    this._NgControlStatusGroup_35_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_35_4);
    this._text_36 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray4(4,'class','sr-only','for','loginEmail'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Username',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','input-group mb-2 mr-sm-2 mb-sm-0'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                            ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_42,'i',new import3.InlineArray2(2,'class','fa fa-envelope'),(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                            ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_40,'input',new import3.InlineArray16(10,'class','form-control form-control-xs','id','loginEmail','placeholder','Email','required','','type','email'),(null as any));
    this._text_46 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray4(4,'class','sr-only','for','loginPassword'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Password',(null as any));
    this._text_50 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','input-group mb-2 mr-2 mb-sm-0'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                            ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'div',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_53,'i',new import3.InlineArray2(2,'class','fa fa-key'),(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n                            ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_51,'input',new import3.InlineArray16(10,'class','form-control form-control-xs','id','loginPassword','placeholder','Password','required','','type','password'),(null as any));
    this._text_57 = this.renderer.createText(this._el_51,'\n                        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_35,'button',new import3.InlineArray4(4,'class','btn btn-primary btn-sm mr-2','type','submit'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Login',(null as any));
    this._text_61 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_35,'button',new import3.InlineArray4(4,'class','btn btn-primary btn-sm mr-2','type','button'),(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_62,'i',new import3.InlineArray2(2,'class','fa fa-facebook'),(null as any));
    this._text_64 = this.renderer.createText(this._el_62,' Facebook',(null as any));
    this._text_65 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_35,'button',new import3.InlineArray4(4,'class','btn btn-primary btn-sm mr-2','type','button'),(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_66,'i',new import3.InlineArray2(2,'class','fa fa-google'),(null as any));
    this._text_68 = this.renderer.createText(this._el_66,' Google',(null as any));
    this._text_69 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._text_70 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_71 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_72 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_0,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_75 = new import16.ViewContainer(75,0,this,this._el_75);
    this._RouterOutlet_75_5 = new import17.Wrapper_RouterOutlet(this.parentView.injectorGet(import19.RouterOutletMap,this.parentIndex),this._vc_75.vcRef,this.parentView.injectorGet(import20.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_18));
    this._NgForm_18_3.subscribe(this,this.eventHandler(this.handleEvent_18),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_22));
    this._NgModel_22_5.subscribe(this,this.eventHandler(this.handleEvent_22),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_35));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3.context; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import23.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_5.context; }
    if (((token === import24.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import25.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7.context; }
    if (((token === import26.NgForm) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgForm_18_3.context; }
    if (((token === import27.ControlContainer) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ControlContainer_18_4; }
    if (((token === import25.NgControlStatusGroup) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControlStatusGroup_18_5.context; }
    if (((token === import26.NgForm) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgForm_35_3.context; }
    if (((token === import27.ControlContainer) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._ControlContainer_35_4; }
    if (((token === import25.NgControlStatusGroup) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControlStatusGroup_35_5.context; }
    if (((token === import28.RouterOutlet) && (75 === requestNodeIndex))) { return this._RouterOutlet_75_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    this._NgControlStatusGroup_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    this._DefaultValueAccessor_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = 'search';
    this._NgModel_22_5.check_name(currVal_22_1_0,throwOnChange,false);
    const currVal_22_1_1:any = this.context.search;
    this._NgModel_22_5.check_model(currVal_22_1_1,throwOnChange,false);
    this._NgModel_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_7.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgForm_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    this._NgControlStatusGroup_35_5.ngDoCheck(this,this._el_35,throwOnChange);
    this._RouterOutlet_75_5.ngDoCheck(this,this._el_75,throwOnChange);
    this._vc_75.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_18_5.checkHost(this,this,this._el_18,throwOnChange);
    this._NgControlStatus_22_7.checkHost(this,this,this._el_22,throwOnChange);
    this._NgControlStatusGroup_35_5.checkHost(this,this,this._el_35,throwOnChange);
  }
  destroyInternal():void {
    this._vc_75.destroyNestedViews();
    this._NgModel_22_5.ngOnDestroy();
    this._NgForm_18_3.ngOnDestroy();
    this._NgForm_35_3.ngOnDestroy();
    this._RouterOutlet_75_5.ngOnDestroy();
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_18_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.doSearch()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_22_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.search = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_35_3.handleEvent(eventName,$event) && result);
    return result;
  }
}